const products = [
  { name: "Reverse Horn", price: 165 },
  { name: "TT Horn", price: 410 },
  { name: "Fuse Socket with wire", price: 45 },
  { name: "Tickly Wire", price: 4.2 },
  { name: "Indicator Assly. Commet", price: 180 },
  { name: "Indicator Assly. 2214", price: 145 },
  { name: "Wiper Blade Push", price: 290 },
  { name: "Wiper Arm Push", price: 305 },
  { name: "Wiper Lock", price: 8 },
  { name: "Wiper Motor", price: 1850 },
  { name: "Wire Bundle", price: 490 },
  { name: "Head Light Seal Beem", price: 200 },
  { name: "Head Light Inner Ring", price: 80 },
  { name: "Head Light Dom.", price: 435 },
  { name: "Sleev (Wire Cover) 10MM - 100 Mtr", price: 465 },
  { name: "Sleev (Wire Cover) 12MM - 100 Mtr", price: 70 },
  { name: "Battery Terminal", price: 12 },
  { name: "Glow 2441 Bulb", price: 23 },
  { name: "Kiran Light", price: 128 },
  { name: "Headlight Bulb", price: 85 },
  { name: "TV Type Side Mirror", price: 182 },
  { name: "Beading Mirror", price: 240 },
  { name: "Wiper Wheel Box", price: 65 },
  { name: "Micro Relay", price: 40 },
  { name: "Push Pull Switch", price: 120 },
  { name: "Arm Side Rod", price: 1850 },
  { name: "Combination Switch", price: 700 },
  { name: "Disel Tank Cap", price: 200 },
  { name: "Roof Lamp", price: 55 },
  { name: "3 Pin Holder", price: 2.5 },
  { name: "Fuse", price: 160 },
  { name: "Headlamp Relay", price: 95 },
  { name: "Music Flasher", price: 170 },
  { name: "Wiper Blade Bolt", price: 20 }
];
